#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitchainWeb
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_Bitchain")]
	public partial class BaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBanco(Banco instance);
    partial void UpdateBanco(Banco instance);
    partial void DeleteBanco(Banco instance);
    partial void InsertUsuarioLogado(UsuarioLogado instance);
    partial void UpdateUsuarioLogado(UsuarioLogado instance);
    partial void DeleteUsuarioLogado(UsuarioLogado instance);
    partial void InsertConta(Conta instance);
    partial void UpdateConta(Conta instance);
    partial void DeleteConta(Conta instance);
    partial void InsertListaMoeda(ListaMoeda instance);
    partial void UpdateListaMoeda(ListaMoeda instance);
    partial void DeleteListaMoeda(ListaMoeda instance);
    partial void InsertMenu_Web(Menu_Web instance);
    partial void UpdateMenu_Web(Menu_Web instance);
    partial void DeleteMenu_Web(Menu_Web instance);
    partial void InsertMenu_Web_Permissao(Menu_Web_Permissao instance);
    partial void UpdateMenu_Web_Permissao(Menu_Web_Permissao instance);
    partial void DeleteMenu_Web_Permissao(Menu_Web_Permissao instance);
    partial void InsertParamSite(ParamSite instance);
    partial void UpdateParamSite(ParamSite instance);
    partial void DeleteParamSite(ParamSite instance);
    partial void InsertPerfil(Perfil instance);
    partial void UpdatePerfil(Perfil instance);
    partial void DeletePerfil(Perfil instance);
    partial void InsertSistema(Sistema instance);
    partial void UpdateSistema(Sistema instance);
    partial void DeleteSistema(Sistema instance);
    partial void InsertTransacao(Transacao instance);
    partial void UpdateTransacao(Transacao instance);
    partial void DeleteTransacao(Transacao instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    #endregion
		
		public BaseDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BaseConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Banco> Bancos
		{
			get
			{
				return this.GetTable<Banco>();
			}
		}
		
		public System.Data.Linq.Table<UsuarioLogado> UsuarioLogados
		{
			get
			{
				return this.GetTable<UsuarioLogado>();
			}
		}
		
		public System.Data.Linq.Table<Conta> Contas
		{
			get
			{
				return this.GetTable<Conta>();
			}
		}
		
		public System.Data.Linq.Table<ListaMoeda> ListaMoedas
		{
			get
			{
				return this.GetTable<ListaMoeda>();
			}
		}
		
		public System.Data.Linq.Table<Menu_Web> Menu_Webs
		{
			get
			{
				return this.GetTable<Menu_Web>();
			}
		}
		
		public System.Data.Linq.Table<Menu_Web_Permissao> Menu_Web_Permissaos
		{
			get
			{
				return this.GetTable<Menu_Web_Permissao>();
			}
		}
		
		public System.Data.Linq.Table<ParamSite> ParamSites
		{
			get
			{
				return this.GetTable<ParamSite>();
			}
		}
		
		public System.Data.Linq.Table<Perfil> Perfils
		{
			get
			{
				return this.GetTable<Perfil>();
			}
		}
		
		public System.Data.Linq.Table<Sistema> Sistemas
		{
			get
			{
				return this.GetTable<Sistema>();
			}
		}
		
		public System.Data.Linq.Table<Transacao> Transacaos
		{
			get
			{
				return this.GetTable<Transacao>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<vw_lstTransacao> vw_lstTransacaos
		{
			get
			{
				return this.GetTable<vw_lstTransacao>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Banco")]
	public partial class Banco : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_BANCO;
		
		private string _NM_DESCRICAO;
		
		private string _NR_BANCO;
		
		private EntitySet<Conta> _Contas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_BANCOChanging(int value);
    partial void OnID_BANCOChanged();
    partial void OnNM_DESCRICAOChanging(string value);
    partial void OnNM_DESCRICAOChanged();
    partial void OnNR_BANCOChanging(string value);
    partial void OnNR_BANCOChanged();
    #endregion
		
		public Banco()
		{
			this._Contas = new EntitySet<Conta>(new Action<Conta>(this.attach_Contas), new Action<Conta>(this.detach_Contas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_BANCO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_BANCO
		{
			get
			{
				return this._ID_BANCO;
			}
			set
			{
				if ((this._ID_BANCO != value))
				{
					this.OnID_BANCOChanging(value);
					this.SendPropertyChanging();
					this._ID_BANCO = value;
					this.SendPropertyChanged("ID_BANCO");
					this.OnID_BANCOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_DESCRICAO", DbType="VarChar(100)")]
		public string NM_DESCRICAO
		{
			get
			{
				return this._NM_DESCRICAO;
			}
			set
			{
				if ((this._NM_DESCRICAO != value))
				{
					this.OnNM_DESCRICAOChanging(value);
					this.SendPropertyChanging();
					this._NM_DESCRICAO = value;
					this.SendPropertyChanged("NM_DESCRICAO");
					this.OnNM_DESCRICAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NR_BANCO", DbType="VarChar(5)")]
		public string NR_BANCO
		{
			get
			{
				return this._NR_BANCO;
			}
			set
			{
				if ((this._NR_BANCO != value))
				{
					this.OnNR_BANCOChanging(value);
					this.SendPropertyChanging();
					this._NR_BANCO = value;
					this.SendPropertyChanged("NR_BANCO");
					this.OnNR_BANCOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Banco_Conta", Storage="_Contas", ThisKey="ID_BANCO", OtherKey="ID_BANCO")]
		public EntitySet<Conta> Contas
		{
			get
			{
				return this._Contas;
			}
			set
			{
				this._Contas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Contas(Conta entity)
		{
			this.SendPropertyChanging();
			entity.Banco = this;
		}
		
		private void detach_Contas(Conta entity)
		{
			this.SendPropertyChanging();
			entity.Banco = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UsuarioLogado")]
	public partial class UsuarioLogado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_USUARIOLOGADO;
		
		private System.Nullable<int> _ID_USUARIO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_USUARIOLOGADOChanging(int value);
    partial void OnID_USUARIOLOGADOChanged();
    partial void OnID_USUARIOChanging(System.Nullable<int> value);
    partial void OnID_USUARIOChanged();
    #endregion
		
		public UsuarioLogado()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIOLOGADO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_USUARIOLOGADO
		{
			get
			{
				return this._ID_USUARIOLOGADO;
			}
			set
			{
				if ((this._ID_USUARIOLOGADO != value))
				{
					this.OnID_USUARIOLOGADOChanging(value);
					this.SendPropertyChanging();
					this._ID_USUARIOLOGADO = value;
					this.SendPropertyChanged("ID_USUARIOLOGADO");
					this.OnID_USUARIOLOGADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", DbType="Int")]
		public System.Nullable<int> ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this.OnID_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._ID_USUARIO = value;
					this.SendPropertyChanged("ID_USUARIO");
					this.OnID_USUARIOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Conta")]
	public partial class Conta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CONTA;
		
		private int _ID_USUARIO;
		
		private int _ID_BANCO;
		
		private string _NR_AGENCIA;
		
		private string _NR_CCORRENTE;
		
		private string _NR_DV;
		
		private System.Nullable<decimal> _VL_SALDO;
		
		private System.Nullable<byte> _FL_HABILITA;
		
		private System.Nullable<System.DateTime> _DT_CADASTRO;
		
		private System.Nullable<int> _ID_USUARIOCADASTRO;
		
		private EntityRef<Banco> _Banco;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CONTAChanging(int value);
    partial void OnID_CONTAChanged();
    partial void OnID_USUARIOChanging(int value);
    partial void OnID_USUARIOChanged();
    partial void OnID_BANCOChanging(int value);
    partial void OnID_BANCOChanged();
    partial void OnNR_AGENCIAChanging(string value);
    partial void OnNR_AGENCIAChanged();
    partial void OnNR_CCORRENTEChanging(string value);
    partial void OnNR_CCORRENTEChanged();
    partial void OnNR_DVChanging(string value);
    partial void OnNR_DVChanged();
    partial void OnVL_SALDOChanging(System.Nullable<decimal> value);
    partial void OnVL_SALDOChanged();
    partial void OnFL_HABILITAChanging(System.Nullable<byte> value);
    partial void OnFL_HABILITAChanged();
    partial void OnDT_CADASTROChanging(System.Nullable<System.DateTime> value);
    partial void OnDT_CADASTROChanged();
    partial void OnID_USUARIOCADASTROChanging(System.Nullable<int> value);
    partial void OnID_USUARIOCADASTROChanged();
    #endregion
		
		public Conta()
		{
			this._Banco = default(EntityRef<Banco>);
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CONTA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_CONTA
		{
			get
			{
				return this._ID_CONTA;
			}
			set
			{
				if ((this._ID_CONTA != value))
				{
					this.OnID_CONTAChanging(value);
					this.SendPropertyChanging();
					this._ID_CONTA = value;
					this.SendPropertyChanged("ID_CONTA");
					this.OnID_CONTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", DbType="Int NOT NULL")]
		public int ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._ID_USUARIO = value;
					this.SendPropertyChanged("ID_USUARIO");
					this.OnID_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_BANCO", DbType="Int NOT NULL")]
		public int ID_BANCO
		{
			get
			{
				return this._ID_BANCO;
			}
			set
			{
				if ((this._ID_BANCO != value))
				{
					if (this._Banco.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_BANCOChanging(value);
					this.SendPropertyChanging();
					this._ID_BANCO = value;
					this.SendPropertyChanged("ID_BANCO");
					this.OnID_BANCOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NR_AGENCIA", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string NR_AGENCIA
		{
			get
			{
				return this._NR_AGENCIA;
			}
			set
			{
				if ((this._NR_AGENCIA != value))
				{
					this.OnNR_AGENCIAChanging(value);
					this.SendPropertyChanging();
					this._NR_AGENCIA = value;
					this.SendPropertyChanged("NR_AGENCIA");
					this.OnNR_AGENCIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NR_CCORRENTE", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NR_CCORRENTE
		{
			get
			{
				return this._NR_CCORRENTE;
			}
			set
			{
				if ((this._NR_CCORRENTE != value))
				{
					this.OnNR_CCORRENTEChanging(value);
					this.SendPropertyChanging();
					this._NR_CCORRENTE = value;
					this.SendPropertyChanged("NR_CCORRENTE");
					this.OnNR_CCORRENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NR_DV", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string NR_DV
		{
			get
			{
				return this._NR_DV;
			}
			set
			{
				if ((this._NR_DV != value))
				{
					this.OnNR_DVChanging(value);
					this.SendPropertyChanging();
					this._NR_DV = value;
					this.SendPropertyChanged("NR_DV");
					this.OnNR_DVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VL_SALDO", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> VL_SALDO
		{
			get
			{
				return this._VL_SALDO;
			}
			set
			{
				if ((this._VL_SALDO != value))
				{
					this.OnVL_SALDOChanging(value);
					this.SendPropertyChanging();
					this._VL_SALDO = value;
					this.SendPropertyChanged("VL_SALDO");
					this.OnVL_SALDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_HABILITA", DbType="TinyInt")]
		public System.Nullable<byte> FL_HABILITA
		{
			get
			{
				return this._FL_HABILITA;
			}
			set
			{
				if ((this._FL_HABILITA != value))
				{
					this.OnFL_HABILITAChanging(value);
					this.SendPropertyChanging();
					this._FL_HABILITA = value;
					this.SendPropertyChanged("FL_HABILITA");
					this.OnFL_HABILITAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_CADASTRO", DbType="DateTime")]
		public System.Nullable<System.DateTime> DT_CADASTRO
		{
			get
			{
				return this._DT_CADASTRO;
			}
			set
			{
				if ((this._DT_CADASTRO != value))
				{
					this.OnDT_CADASTROChanging(value);
					this.SendPropertyChanging();
					this._DT_CADASTRO = value;
					this.SendPropertyChanged("DT_CADASTRO");
					this.OnDT_CADASTROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIOCADASTRO", DbType="Int")]
		public System.Nullable<int> ID_USUARIOCADASTRO
		{
			get
			{
				return this._ID_USUARIOCADASTRO;
			}
			set
			{
				if ((this._ID_USUARIOCADASTRO != value))
				{
					this.OnID_USUARIOCADASTROChanging(value);
					this.SendPropertyChanging();
					this._ID_USUARIOCADASTRO = value;
					this.SendPropertyChanged("ID_USUARIOCADASTRO");
					this.OnID_USUARIOCADASTROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Banco_Conta", Storage="_Banco", ThisKey="ID_BANCO", OtherKey="ID_BANCO", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Banco Banco
		{
			get
			{
				return this._Banco.Entity;
			}
			set
			{
				Banco previousValue = this._Banco.Entity;
				if (((previousValue != value) 
							|| (this._Banco.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Banco.Entity = null;
						previousValue.Contas.Remove(this);
					}
					this._Banco.Entity = value;
					if ((value != null))
					{
						value.Contas.Add(this);
						this._ID_BANCO = value.ID_BANCO;
					}
					else
					{
						this._ID_BANCO = default(int);
					}
					this.SendPropertyChanged("Banco");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Conta", Storage="_Usuario", ThisKey="ID_USUARIO", OtherKey="ID_USUARIO", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Contas.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Contas.Add(this);
						this._ID_USUARIO = value.ID_USUARIO;
					}
					else
					{
						this._ID_USUARIO = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ListaMoeda")]
	public partial class ListaMoeda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_MOEDA;
		
		private string _NM_SIGLA;
		
		private string _NM_DESCRICAO;
		
		private System.Nullable<decimal> _VL_BASE;
		
		private System.Nullable<decimal> _VL_REAL;
		
		private System.Nullable<byte> _FL_HABILITA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MOEDAChanging(int value);
    partial void OnID_MOEDAChanged();
    partial void OnNM_SIGLAChanging(string value);
    partial void OnNM_SIGLAChanged();
    partial void OnNM_DESCRICAOChanging(string value);
    partial void OnNM_DESCRICAOChanged();
    partial void OnVL_BASEChanging(System.Nullable<decimal> value);
    partial void OnVL_BASEChanged();
    partial void OnVL_REALChanging(System.Nullable<decimal> value);
    partial void OnVL_REALChanged();
    partial void OnFL_HABILITAChanging(System.Nullable<byte> value);
    partial void OnFL_HABILITAChanged();
    #endregion
		
		public ListaMoeda()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MOEDA", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_MOEDA
		{
			get
			{
				return this._ID_MOEDA;
			}
			set
			{
				if ((this._ID_MOEDA != value))
				{
					this.OnID_MOEDAChanging(value);
					this.SendPropertyChanging();
					this._ID_MOEDA = value;
					this.SendPropertyChanged("ID_MOEDA");
					this.OnID_MOEDAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_SIGLA", DbType="VarChar(5)")]
		public string NM_SIGLA
		{
			get
			{
				return this._NM_SIGLA;
			}
			set
			{
				if ((this._NM_SIGLA != value))
				{
					this.OnNM_SIGLAChanging(value);
					this.SendPropertyChanging();
					this._NM_SIGLA = value;
					this.SendPropertyChanged("NM_SIGLA");
					this.OnNM_SIGLAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_DESCRICAO", DbType="VarChar(50)")]
		public string NM_DESCRICAO
		{
			get
			{
				return this._NM_DESCRICAO;
			}
			set
			{
				if ((this._NM_DESCRICAO != value))
				{
					this.OnNM_DESCRICAOChanging(value);
					this.SendPropertyChanging();
					this._NM_DESCRICAO = value;
					this.SendPropertyChanged("NM_DESCRICAO");
					this.OnNM_DESCRICAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VL_BASE", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> VL_BASE
		{
			get
			{
				return this._VL_BASE;
			}
			set
			{
				if ((this._VL_BASE != value))
				{
					this.OnVL_BASEChanging(value);
					this.SendPropertyChanging();
					this._VL_BASE = value;
					this.SendPropertyChanged("VL_BASE");
					this.OnVL_BASEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VL_REAL", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> VL_REAL
		{
			get
			{
				return this._VL_REAL;
			}
			set
			{
				if ((this._VL_REAL != value))
				{
					this.OnVL_REALChanging(value);
					this.SendPropertyChanging();
					this._VL_REAL = value;
					this.SendPropertyChanged("VL_REAL");
					this.OnVL_REALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_HABILITA", DbType="TinyInt")]
		public System.Nullable<byte> FL_HABILITA
		{
			get
			{
				return this._FL_HABILITA;
			}
			set
			{
				if ((this._FL_HABILITA != value))
				{
					this.OnFL_HABILITAChanging(value);
					this.SendPropertyChanging();
					this._FL_HABILITA = value;
					this.SendPropertyChanged("FL_HABILITA");
					this.OnFL_HABILITAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Menu_Web")]
	public partial class Menu_Web : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_MENU_WEB;
		
		private System.Nullable<int> _ID_MENU_PAI;
		
		private string _NM_DESCRICAO;
		
		private string _NM_URL;
		
		private int _ID_Sistema;
		
		private EntitySet<Menu_Web_Permissao> _Menu_Web_Permissaos;
		
		private EntityRef<Sistema> _Sistema;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MENU_WEBChanging(int value);
    partial void OnID_MENU_WEBChanged();
    partial void OnID_MENU_PAIChanging(System.Nullable<int> value);
    partial void OnID_MENU_PAIChanged();
    partial void OnNM_DESCRICAOChanging(string value);
    partial void OnNM_DESCRICAOChanged();
    partial void OnNM_URLChanging(string value);
    partial void OnNM_URLChanged();
    partial void OnID_SistemaChanging(int value);
    partial void OnID_SistemaChanged();
    #endregion
		
		public Menu_Web()
		{
			this._Menu_Web_Permissaos = new EntitySet<Menu_Web_Permissao>(new Action<Menu_Web_Permissao>(this.attach_Menu_Web_Permissaos), new Action<Menu_Web_Permissao>(this.detach_Menu_Web_Permissaos));
			this._Sistema = default(EntityRef<Sistema>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MENU_WEB", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_MENU_WEB
		{
			get
			{
				return this._ID_MENU_WEB;
			}
			set
			{
				if ((this._ID_MENU_WEB != value))
				{
					this.OnID_MENU_WEBChanging(value);
					this.SendPropertyChanging();
					this._ID_MENU_WEB = value;
					this.SendPropertyChanged("ID_MENU_WEB");
					this.OnID_MENU_WEBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MENU_PAI", DbType="Int")]
		public System.Nullable<int> ID_MENU_PAI
		{
			get
			{
				return this._ID_MENU_PAI;
			}
			set
			{
				if ((this._ID_MENU_PAI != value))
				{
					this.OnID_MENU_PAIChanging(value);
					this.SendPropertyChanging();
					this._ID_MENU_PAI = value;
					this.SendPropertyChanged("ID_MENU_PAI");
					this.OnID_MENU_PAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_DESCRICAO", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NM_DESCRICAO
		{
			get
			{
				return this._NM_DESCRICAO;
			}
			set
			{
				if ((this._NM_DESCRICAO != value))
				{
					this.OnNM_DESCRICAOChanging(value);
					this.SendPropertyChanging();
					this._NM_DESCRICAO = value;
					this.SendPropertyChanged("NM_DESCRICAO");
					this.OnNM_DESCRICAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_URL", DbType="VarChar(120)")]
		public string NM_URL
		{
			get
			{
				return this._NM_URL;
			}
			set
			{
				if ((this._NM_URL != value))
				{
					this.OnNM_URLChanging(value);
					this.SendPropertyChanging();
					this._NM_URL = value;
					this.SendPropertyChanged("NM_URL");
					this.OnNM_URLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Sistema", DbType="Int NOT NULL")]
		public int ID_Sistema
		{
			get
			{
				return this._ID_Sistema;
			}
			set
			{
				if ((this._ID_Sistema != value))
				{
					if (this._Sistema.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_SistemaChanging(value);
					this.SendPropertyChanging();
					this._ID_Sistema = value;
					this.SendPropertyChanged("ID_Sistema");
					this.OnID_SistemaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Menu_Web_Menu_Web_Permissao", Storage="_Menu_Web_Permissaos", ThisKey="ID_MENU_WEB", OtherKey="ID_MENU_WEB")]
		public EntitySet<Menu_Web_Permissao> Menu_Web_Permissaos
		{
			get
			{
				return this._Menu_Web_Permissaos;
			}
			set
			{
				this._Menu_Web_Permissaos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sistema_Menu_Web", Storage="_Sistema", ThisKey="ID_Sistema", OtherKey="ID_SISTEMA", IsForeignKey=true)]
		public Sistema Sistema
		{
			get
			{
				return this._Sistema.Entity;
			}
			set
			{
				Sistema previousValue = this._Sistema.Entity;
				if (((previousValue != value) 
							|| (this._Sistema.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sistema.Entity = null;
						previousValue.Menu_Webs.Remove(this);
					}
					this._Sistema.Entity = value;
					if ((value != null))
					{
						value.Menu_Webs.Add(this);
						this._ID_Sistema = value.ID_SISTEMA;
					}
					else
					{
						this._ID_Sistema = default(int);
					}
					this.SendPropertyChanged("Sistema");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Menu_Web_Permissaos(Menu_Web_Permissao entity)
		{
			this.SendPropertyChanging();
			entity.Menu_Web = this;
		}
		
		private void detach_Menu_Web_Permissaos(Menu_Web_Permissao entity)
		{
			this.SendPropertyChanging();
			entity.Menu_Web = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Menu_Web_Permissao")]
	public partial class Menu_Web_Permissao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_MENU_WEB;
		
		private int _ID_USUARIO;
		
		private EntityRef<Menu_Web> _Menu_Web;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MENU_WEBChanging(int value);
    partial void OnID_MENU_WEBChanged();
    partial void OnID_USUARIOChanging(int value);
    partial void OnID_USUARIOChanged();
    #endregion
		
		public Menu_Web_Permissao()
		{
			this._Menu_Web = default(EntityRef<Menu_Web>);
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MENU_WEB", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_MENU_WEB
		{
			get
			{
				return this._ID_MENU_WEB;
			}
			set
			{
				if ((this._ID_MENU_WEB != value))
				{
					if (this._Menu_Web.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_MENU_WEBChanging(value);
					this.SendPropertyChanging();
					this._ID_MENU_WEB = value;
					this.SendPropertyChanged("ID_MENU_WEB");
					this.OnID_MENU_WEBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._ID_USUARIO = value;
					this.SendPropertyChanged("ID_USUARIO");
					this.OnID_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Menu_Web_Menu_Web_Permissao", Storage="_Menu_Web", ThisKey="ID_MENU_WEB", OtherKey="ID_MENU_WEB", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Menu_Web Menu_Web
		{
			get
			{
				return this._Menu_Web.Entity;
			}
			set
			{
				Menu_Web previousValue = this._Menu_Web.Entity;
				if (((previousValue != value) 
							|| (this._Menu_Web.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Menu_Web.Entity = null;
						previousValue.Menu_Web_Permissaos.Remove(this);
					}
					this._Menu_Web.Entity = value;
					if ((value != null))
					{
						value.Menu_Web_Permissaos.Add(this);
						this._ID_MENU_WEB = value.ID_MENU_WEB;
					}
					else
					{
						this._ID_MENU_WEB = default(int);
					}
					this.SendPropertyChanged("Menu_Web");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Menu_Web_Permissao", Storage="_Usuario", ThisKey="ID_USUARIO", OtherKey="ID_USUARIO", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Menu_Web_Permissaos.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Menu_Web_Permissaos.Add(this);
						this._ID_USUARIO = value.ID_USUARIO;
					}
					else
					{
						this._ID_USUARIO = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ParamSite")]
	public partial class ParamSite : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _ID_PARAMSITE;
		
		private string _NM_URLSITE;
		
		private string _NM_SMTP_USER;
		
		private string _NM_SMTP_SRV;
		
		private string _NM_SMTP_PASS;
		
		private System.Nullable<byte> _TP_SMTP_AUTENTIC;
		
		private System.Nullable<int> _NR_SMTP_PORT;
		
		private string _DS_EMAILBCC;
		
		private string _NM_SMTP_EMAIL;
		
		private string _NM_DIRETORIO_LOGO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PARAMSITEChanging(byte value);
    partial void OnID_PARAMSITEChanged();
    partial void OnNM_URLSITEChanging(string value);
    partial void OnNM_URLSITEChanged();
    partial void OnNM_SMTP_USERChanging(string value);
    partial void OnNM_SMTP_USERChanged();
    partial void OnNM_SMTP_SRVChanging(string value);
    partial void OnNM_SMTP_SRVChanged();
    partial void OnNM_SMTP_PASSChanging(string value);
    partial void OnNM_SMTP_PASSChanged();
    partial void OnTP_SMTP_AUTENTICChanging(System.Nullable<byte> value);
    partial void OnTP_SMTP_AUTENTICChanged();
    partial void OnNR_SMTP_PORTChanging(System.Nullable<int> value);
    partial void OnNR_SMTP_PORTChanged();
    partial void OnDS_EMAILBCCChanging(string value);
    partial void OnDS_EMAILBCCChanged();
    partial void OnNM_SMTP_EMAILChanging(string value);
    partial void OnNM_SMTP_EMAILChanged();
    partial void OnNM_DIRETORIO_LOGOChanging(string value);
    partial void OnNM_DIRETORIO_LOGOChanged();
    #endregion
		
		public ParamSite()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PARAMSITE", AutoSync=AutoSync.OnInsert, DbType="TinyInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public byte ID_PARAMSITE
		{
			get
			{
				return this._ID_PARAMSITE;
			}
			set
			{
				if ((this._ID_PARAMSITE != value))
				{
					this.OnID_PARAMSITEChanging(value);
					this.SendPropertyChanging();
					this._ID_PARAMSITE = value;
					this.SendPropertyChanged("ID_PARAMSITE");
					this.OnID_PARAMSITEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_URLSITE", DbType="VarChar(512)")]
		public string NM_URLSITE
		{
			get
			{
				return this._NM_URLSITE;
			}
			set
			{
				if ((this._NM_URLSITE != value))
				{
					this.OnNM_URLSITEChanging(value);
					this.SendPropertyChanging();
					this._NM_URLSITE = value;
					this.SendPropertyChanged("NM_URLSITE");
					this.OnNM_URLSITEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_SMTP_USER", DbType="VarChar(100)")]
		public string NM_SMTP_USER
		{
			get
			{
				return this._NM_SMTP_USER;
			}
			set
			{
				if ((this._NM_SMTP_USER != value))
				{
					this.OnNM_SMTP_USERChanging(value);
					this.SendPropertyChanging();
					this._NM_SMTP_USER = value;
					this.SendPropertyChanged("NM_SMTP_USER");
					this.OnNM_SMTP_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_SMTP_SRV", DbType="VarChar(50)")]
		public string NM_SMTP_SRV
		{
			get
			{
				return this._NM_SMTP_SRV;
			}
			set
			{
				if ((this._NM_SMTP_SRV != value))
				{
					this.OnNM_SMTP_SRVChanging(value);
					this.SendPropertyChanging();
					this._NM_SMTP_SRV = value;
					this.SendPropertyChanged("NM_SMTP_SRV");
					this.OnNM_SMTP_SRVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_SMTP_PASS", DbType="VarChar(50)")]
		public string NM_SMTP_PASS
		{
			get
			{
				return this._NM_SMTP_PASS;
			}
			set
			{
				if ((this._NM_SMTP_PASS != value))
				{
					this.OnNM_SMTP_PASSChanging(value);
					this.SendPropertyChanging();
					this._NM_SMTP_PASS = value;
					this.SendPropertyChanged("NM_SMTP_PASS");
					this.OnNM_SMTP_PASSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TP_SMTP_AUTENTIC", DbType="TinyInt")]
		public System.Nullable<byte> TP_SMTP_AUTENTIC
		{
			get
			{
				return this._TP_SMTP_AUTENTIC;
			}
			set
			{
				if ((this._TP_SMTP_AUTENTIC != value))
				{
					this.OnTP_SMTP_AUTENTICChanging(value);
					this.SendPropertyChanging();
					this._TP_SMTP_AUTENTIC = value;
					this.SendPropertyChanged("TP_SMTP_AUTENTIC");
					this.OnTP_SMTP_AUTENTICChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NR_SMTP_PORT", DbType="Int")]
		public System.Nullable<int> NR_SMTP_PORT
		{
			get
			{
				return this._NR_SMTP_PORT;
			}
			set
			{
				if ((this._NR_SMTP_PORT != value))
				{
					this.OnNR_SMTP_PORTChanging(value);
					this.SendPropertyChanging();
					this._NR_SMTP_PORT = value;
					this.SendPropertyChanged("NR_SMTP_PORT");
					this.OnNR_SMTP_PORTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DS_EMAILBCC", DbType="VarChar(100)")]
		public string DS_EMAILBCC
		{
			get
			{
				return this._DS_EMAILBCC;
			}
			set
			{
				if ((this._DS_EMAILBCC != value))
				{
					this.OnDS_EMAILBCCChanging(value);
					this.SendPropertyChanging();
					this._DS_EMAILBCC = value;
					this.SendPropertyChanged("DS_EMAILBCC");
					this.OnDS_EMAILBCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_SMTP_EMAIL", DbType="VarChar(100)")]
		public string NM_SMTP_EMAIL
		{
			get
			{
				return this._NM_SMTP_EMAIL;
			}
			set
			{
				if ((this._NM_SMTP_EMAIL != value))
				{
					this.OnNM_SMTP_EMAILChanging(value);
					this.SendPropertyChanging();
					this._NM_SMTP_EMAIL = value;
					this.SendPropertyChanged("NM_SMTP_EMAIL");
					this.OnNM_SMTP_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_DIRETORIO_LOGO", DbType="VarChar(MAX)")]
		public string NM_DIRETORIO_LOGO
		{
			get
			{
				return this._NM_DIRETORIO_LOGO;
			}
			set
			{
				if ((this._NM_DIRETORIO_LOGO != value))
				{
					this.OnNM_DIRETORIO_LOGOChanging(value);
					this.SendPropertyChanging();
					this._NM_DIRETORIO_LOGO = value;
					this.SendPropertyChanged("NM_DIRETORIO_LOGO");
					this.OnNM_DIRETORIO_LOGOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Perfil")]
	public partial class Perfil : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_PERFIL;
		
		private string _NM_DESCRICAO;
		
		private EntitySet<Usuario> _Usuarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PERFILChanging(int value);
    partial void OnID_PERFILChanged();
    partial void OnNM_DESCRICAOChanging(string value);
    partial void OnNM_DESCRICAOChanged();
    #endregion
		
		public Perfil()
		{
			this._Usuarios = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuarios), new Action<Usuario>(this.detach_Usuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PERFIL", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_PERFIL
		{
			get
			{
				return this._ID_PERFIL;
			}
			set
			{
				if ((this._ID_PERFIL != value))
				{
					this.OnID_PERFILChanging(value);
					this.SendPropertyChanging();
					this._ID_PERFIL = value;
					this.SendPropertyChanged("ID_PERFIL");
					this.OnID_PERFILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_DESCRICAO", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string NM_DESCRICAO
		{
			get
			{
				return this._NM_DESCRICAO;
			}
			set
			{
				if ((this._NM_DESCRICAO != value))
				{
					this.OnNM_DESCRICAOChanging(value);
					this.SendPropertyChanging();
					this._NM_DESCRICAO = value;
					this.SendPropertyChanged("NM_DESCRICAO");
					this.OnNM_DESCRICAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Perfil_Usuario", Storage="_Usuarios", ThisKey="ID_PERFIL", OtherKey="ID_PERFIL")]
		public EntitySet<Usuario> Usuarios
		{
			get
			{
				return this._Usuarios;
			}
			set
			{
				this._Usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Perfil = this;
		}
		
		private void detach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Perfil = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sistema")]
	public partial class Sistema : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_SISTEMA;
		
		private string _NM_DESCRICAO;
		
		private System.DateTime _DT_CADASTRO;
		
		private EntitySet<Menu_Web> _Menu_Webs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_SISTEMAChanging(int value);
    partial void OnID_SISTEMAChanged();
    partial void OnNM_DESCRICAOChanging(string value);
    partial void OnNM_DESCRICAOChanged();
    partial void OnDT_CADASTROChanging(System.DateTime value);
    partial void OnDT_CADASTROChanged();
    #endregion
		
		public Sistema()
		{
			this._Menu_Webs = new EntitySet<Menu_Web>(new Action<Menu_Web>(this.attach_Menu_Webs), new Action<Menu_Web>(this.detach_Menu_Webs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SISTEMA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_SISTEMA
		{
			get
			{
				return this._ID_SISTEMA;
			}
			set
			{
				if ((this._ID_SISTEMA != value))
				{
					this.OnID_SISTEMAChanging(value);
					this.SendPropertyChanging();
					this._ID_SISTEMA = value;
					this.SendPropertyChanged("ID_SISTEMA");
					this.OnID_SISTEMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_DESCRICAO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NM_DESCRICAO
		{
			get
			{
				return this._NM_DESCRICAO;
			}
			set
			{
				if ((this._NM_DESCRICAO != value))
				{
					this.OnNM_DESCRICAOChanging(value);
					this.SendPropertyChanging();
					this._NM_DESCRICAO = value;
					this.SendPropertyChanged("NM_DESCRICAO");
					this.OnNM_DESCRICAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_CADASTRO", DbType="DateTime NOT NULL")]
		public System.DateTime DT_CADASTRO
		{
			get
			{
				return this._DT_CADASTRO;
			}
			set
			{
				if ((this._DT_CADASTRO != value))
				{
					this.OnDT_CADASTROChanging(value);
					this.SendPropertyChanging();
					this._DT_CADASTRO = value;
					this.SendPropertyChanged("DT_CADASTRO");
					this.OnDT_CADASTROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sistema_Menu_Web", Storage="_Menu_Webs", ThisKey="ID_SISTEMA", OtherKey="ID_Sistema")]
		public EntitySet<Menu_Web> Menu_Webs
		{
			get
			{
				return this._Menu_Webs;
			}
			set
			{
				this._Menu_Webs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Menu_Webs(Menu_Web entity)
		{
			this.SendPropertyChanging();
			entity.Sistema = this;
		}
		
		private void detach_Menu_Webs(Menu_Web entity)
		{
			this.SendPropertyChanging();
			entity.Sistema = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Transacao")]
	public partial class Transacao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_TRANSACAO;
		
		private int _ID_USUARIO_DE;
		
		private System.Nullable<int> _ID_CONTA_DE;
		
		private int _ID_USUARIO_PARA;
		
		private System.Nullable<int> _ID_CONTA_PARA;
		
		private decimal _VL_BRUTO;
		
		private System.DateTime _DT_TRANSACAO;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_TRANSACAOChanging(int value);
    partial void OnID_TRANSACAOChanged();
    partial void OnID_USUARIO_DEChanging(int value);
    partial void OnID_USUARIO_DEChanged();
    partial void OnID_CONTA_DEChanging(System.Nullable<int> value);
    partial void OnID_CONTA_DEChanged();
    partial void OnID_USUARIO_PARAChanging(int value);
    partial void OnID_USUARIO_PARAChanged();
    partial void OnID_CONTA_PARAChanging(System.Nullable<int> value);
    partial void OnID_CONTA_PARAChanged();
    partial void OnVL_BRUTOChanging(decimal value);
    partial void OnVL_BRUTOChanged();
    partial void OnDT_TRANSACAOChanging(System.DateTime value);
    partial void OnDT_TRANSACAOChanged();
    #endregion
		
		public Transacao()
		{
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TRANSACAO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_TRANSACAO
		{
			get
			{
				return this._ID_TRANSACAO;
			}
			set
			{
				if ((this._ID_TRANSACAO != value))
				{
					this.OnID_TRANSACAOChanging(value);
					this.SendPropertyChanging();
					this._ID_TRANSACAO = value;
					this.SendPropertyChanged("ID_TRANSACAO");
					this.OnID_TRANSACAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO_DE", DbType="Int NOT NULL")]
		public int ID_USUARIO_DE
		{
			get
			{
				return this._ID_USUARIO_DE;
			}
			set
			{
				if ((this._ID_USUARIO_DE != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_USUARIO_DEChanging(value);
					this.SendPropertyChanging();
					this._ID_USUARIO_DE = value;
					this.SendPropertyChanged("ID_USUARIO_DE");
					this.OnID_USUARIO_DEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CONTA_DE", DbType="Int")]
		public System.Nullable<int> ID_CONTA_DE
		{
			get
			{
				return this._ID_CONTA_DE;
			}
			set
			{
				if ((this._ID_CONTA_DE != value))
				{
					this.OnID_CONTA_DEChanging(value);
					this.SendPropertyChanging();
					this._ID_CONTA_DE = value;
					this.SendPropertyChanged("ID_CONTA_DE");
					this.OnID_CONTA_DEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO_PARA", DbType="Int NOT NULL")]
		public int ID_USUARIO_PARA
		{
			get
			{
				return this._ID_USUARIO_PARA;
			}
			set
			{
				if ((this._ID_USUARIO_PARA != value))
				{
					this.OnID_USUARIO_PARAChanging(value);
					this.SendPropertyChanging();
					this._ID_USUARIO_PARA = value;
					this.SendPropertyChanged("ID_USUARIO_PARA");
					this.OnID_USUARIO_PARAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CONTA_PARA", DbType="Int")]
		public System.Nullable<int> ID_CONTA_PARA
		{
			get
			{
				return this._ID_CONTA_PARA;
			}
			set
			{
				if ((this._ID_CONTA_PARA != value))
				{
					this.OnID_CONTA_PARAChanging(value);
					this.SendPropertyChanging();
					this._ID_CONTA_PARA = value;
					this.SendPropertyChanged("ID_CONTA_PARA");
					this.OnID_CONTA_PARAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VL_BRUTO", DbType="Decimal(20,2) NOT NULL")]
		public decimal VL_BRUTO
		{
			get
			{
				return this._VL_BRUTO;
			}
			set
			{
				if ((this._VL_BRUTO != value))
				{
					this.OnVL_BRUTOChanging(value);
					this.SendPropertyChanging();
					this._VL_BRUTO = value;
					this.SendPropertyChanged("VL_BRUTO");
					this.OnVL_BRUTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_TRANSACAO", DbType="DateTime NOT NULL")]
		public System.DateTime DT_TRANSACAO
		{
			get
			{
				return this._DT_TRANSACAO;
			}
			set
			{
				if ((this._DT_TRANSACAO != value))
				{
					this.OnDT_TRANSACAOChanging(value);
					this.SendPropertyChanging();
					this._DT_TRANSACAO = value;
					this.SendPropertyChanged("DT_TRANSACAO");
					this.OnDT_TRANSACAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Transacao", Storage="_Usuario", ThisKey="ID_USUARIO_DE", OtherKey="ID_USUARIO", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Transacaos.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Transacaos.Add(this);
						this._ID_USUARIO_DE = value.ID_USUARIO;
					}
					else
					{
						this._ID_USUARIO_DE = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_USUARIO;
		
		private string _NM_NOME;
		
		private string _NR_CPF;
		
		private string _NM_EMAIL;
		
		private string _NR_TELEFONE;
		
		private string _NR_CELULAR;
		
		private string _NM_LOGIN;
		
		private string _NM_SENHA;
		
		private System.Nullable<int> _ID_PERFIL;
		
		private System.Nullable<byte> _FL_HABILITA;
		
		private System.Nullable<byte> _FL_TROCA_SENHA;
		
		private string _NM_USUARIO_CADASTRO;
		
		private System.Nullable<System.DateTime> _DT_CADASTRO;
		
		private string _NM_USUARIO_ALTERACAO;
		
		private System.Nullable<System.DateTime> _DT_ALTERACAO;
		
		private System.Nullable<int> _NR_ULTIMO_ACESSO;
		
		private System.Nullable<System.DateTime> _DT_ULTIMO_ACESSO;
		
		private EntitySet<Conta> _Contas;
		
		private EntitySet<Menu_Web_Permissao> _Menu_Web_Permissaos;
		
		private EntitySet<Transacao> _Transacaos;
		
		private EntityRef<Perfil> _Perfil;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_USUARIOChanging(int value);
    partial void OnID_USUARIOChanged();
    partial void OnNM_NOMEChanging(string value);
    partial void OnNM_NOMEChanged();
    partial void OnNR_CPFChanging(string value);
    partial void OnNR_CPFChanged();
    partial void OnNM_EMAILChanging(string value);
    partial void OnNM_EMAILChanged();
    partial void OnNR_TELEFONEChanging(string value);
    partial void OnNR_TELEFONEChanged();
    partial void OnNR_CELULARChanging(string value);
    partial void OnNR_CELULARChanged();
    partial void OnNM_LOGINChanging(string value);
    partial void OnNM_LOGINChanged();
    partial void OnNM_SENHAChanging(string value);
    partial void OnNM_SENHAChanged();
    partial void OnID_PERFILChanging(System.Nullable<int> value);
    partial void OnID_PERFILChanged();
    partial void OnFL_HABILITAChanging(System.Nullable<byte> value);
    partial void OnFL_HABILITAChanged();
    partial void OnFL_TROCA_SENHAChanging(System.Nullable<byte> value);
    partial void OnFL_TROCA_SENHAChanged();
    partial void OnNM_USUARIO_CADASTROChanging(string value);
    partial void OnNM_USUARIO_CADASTROChanged();
    partial void OnDT_CADASTROChanging(System.Nullable<System.DateTime> value);
    partial void OnDT_CADASTROChanged();
    partial void OnNM_USUARIO_ALTERACAOChanging(string value);
    partial void OnNM_USUARIO_ALTERACAOChanged();
    partial void OnDT_ALTERACAOChanging(System.Nullable<System.DateTime> value);
    partial void OnDT_ALTERACAOChanged();
    partial void OnNR_ULTIMO_ACESSOChanging(System.Nullable<int> value);
    partial void OnNR_ULTIMO_ACESSOChanged();
    partial void OnDT_ULTIMO_ACESSOChanging(System.Nullable<System.DateTime> value);
    partial void OnDT_ULTIMO_ACESSOChanged();
    #endregion
		
		public Usuario()
		{
			this._Contas = new EntitySet<Conta>(new Action<Conta>(this.attach_Contas), new Action<Conta>(this.detach_Contas));
			this._Menu_Web_Permissaos = new EntitySet<Menu_Web_Permissao>(new Action<Menu_Web_Permissao>(this.attach_Menu_Web_Permissaos), new Action<Menu_Web_Permissao>(this.detach_Menu_Web_Permissaos));
			this._Transacaos = new EntitySet<Transacao>(new Action<Transacao>(this.attach_Transacaos), new Action<Transacao>(this.detach_Transacaos));
			this._Perfil = default(EntityRef<Perfil>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this.OnID_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._ID_USUARIO = value;
					this.SendPropertyChanged("ID_USUARIO");
					this.OnID_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_NOME", DbType="VarChar(100)")]
		public string NM_NOME
		{
			get
			{
				return this._NM_NOME;
			}
			set
			{
				if ((this._NM_NOME != value))
				{
					this.OnNM_NOMEChanging(value);
					this.SendPropertyChanging();
					this._NM_NOME = value;
					this.SendPropertyChanged("NM_NOME");
					this.OnNM_NOMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NR_CPF", DbType="VarChar(14)")]
		public string NR_CPF
		{
			get
			{
				return this._NR_CPF;
			}
			set
			{
				if ((this._NR_CPF != value))
				{
					this.OnNR_CPFChanging(value);
					this.SendPropertyChanging();
					this._NR_CPF = value;
					this.SendPropertyChanged("NR_CPF");
					this.OnNR_CPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_EMAIL", DbType="VarChar(100)")]
		public string NM_EMAIL
		{
			get
			{
				return this._NM_EMAIL;
			}
			set
			{
				if ((this._NM_EMAIL != value))
				{
					this.OnNM_EMAILChanging(value);
					this.SendPropertyChanging();
					this._NM_EMAIL = value;
					this.SendPropertyChanged("NM_EMAIL");
					this.OnNM_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NR_TELEFONE", DbType="VarChar(25)")]
		public string NR_TELEFONE
		{
			get
			{
				return this._NR_TELEFONE;
			}
			set
			{
				if ((this._NR_TELEFONE != value))
				{
					this.OnNR_TELEFONEChanging(value);
					this.SendPropertyChanging();
					this._NR_TELEFONE = value;
					this.SendPropertyChanged("NR_TELEFONE");
					this.OnNR_TELEFONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NR_CELULAR", DbType="VarChar(25)")]
		public string NR_CELULAR
		{
			get
			{
				return this._NR_CELULAR;
			}
			set
			{
				if ((this._NR_CELULAR != value))
				{
					this.OnNR_CELULARChanging(value);
					this.SendPropertyChanging();
					this._NR_CELULAR = value;
					this.SendPropertyChanged("NR_CELULAR");
					this.OnNR_CELULARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_LOGIN", DbType="VarChar(50)")]
		public string NM_LOGIN
		{
			get
			{
				return this._NM_LOGIN;
			}
			set
			{
				if ((this._NM_LOGIN != value))
				{
					this.OnNM_LOGINChanging(value);
					this.SendPropertyChanging();
					this._NM_LOGIN = value;
					this.SendPropertyChanged("NM_LOGIN");
					this.OnNM_LOGINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_SENHA", DbType="VarChar(10)")]
		public string NM_SENHA
		{
			get
			{
				return this._NM_SENHA;
			}
			set
			{
				if ((this._NM_SENHA != value))
				{
					this.OnNM_SENHAChanging(value);
					this.SendPropertyChanging();
					this._NM_SENHA = value;
					this.SendPropertyChanged("NM_SENHA");
					this.OnNM_SENHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PERFIL", DbType="Int")]
		public System.Nullable<int> ID_PERFIL
		{
			get
			{
				return this._ID_PERFIL;
			}
			set
			{
				if ((this._ID_PERFIL != value))
				{
					if (this._Perfil.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PERFILChanging(value);
					this.SendPropertyChanging();
					this._ID_PERFIL = value;
					this.SendPropertyChanged("ID_PERFIL");
					this.OnID_PERFILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_HABILITA", DbType="TinyInt")]
		public System.Nullable<byte> FL_HABILITA
		{
			get
			{
				return this._FL_HABILITA;
			}
			set
			{
				if ((this._FL_HABILITA != value))
				{
					this.OnFL_HABILITAChanging(value);
					this.SendPropertyChanging();
					this._FL_HABILITA = value;
					this.SendPropertyChanged("FL_HABILITA");
					this.OnFL_HABILITAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_TROCA_SENHA", DbType="TinyInt")]
		public System.Nullable<byte> FL_TROCA_SENHA
		{
			get
			{
				return this._FL_TROCA_SENHA;
			}
			set
			{
				if ((this._FL_TROCA_SENHA != value))
				{
					this.OnFL_TROCA_SENHAChanging(value);
					this.SendPropertyChanging();
					this._FL_TROCA_SENHA = value;
					this.SendPropertyChanged("FL_TROCA_SENHA");
					this.OnFL_TROCA_SENHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_USUARIO_CADASTRO", DbType="VarChar(50)")]
		public string NM_USUARIO_CADASTRO
		{
			get
			{
				return this._NM_USUARIO_CADASTRO;
			}
			set
			{
				if ((this._NM_USUARIO_CADASTRO != value))
				{
					this.OnNM_USUARIO_CADASTROChanging(value);
					this.SendPropertyChanging();
					this._NM_USUARIO_CADASTRO = value;
					this.SendPropertyChanged("NM_USUARIO_CADASTRO");
					this.OnNM_USUARIO_CADASTROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_CADASTRO", DbType="DateTime")]
		public System.Nullable<System.DateTime> DT_CADASTRO
		{
			get
			{
				return this._DT_CADASTRO;
			}
			set
			{
				if ((this._DT_CADASTRO != value))
				{
					this.OnDT_CADASTROChanging(value);
					this.SendPropertyChanging();
					this._DT_CADASTRO = value;
					this.SendPropertyChanged("DT_CADASTRO");
					this.OnDT_CADASTROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_USUARIO_ALTERACAO", DbType="VarChar(50)")]
		public string NM_USUARIO_ALTERACAO
		{
			get
			{
				return this._NM_USUARIO_ALTERACAO;
			}
			set
			{
				if ((this._NM_USUARIO_ALTERACAO != value))
				{
					this.OnNM_USUARIO_ALTERACAOChanging(value);
					this.SendPropertyChanging();
					this._NM_USUARIO_ALTERACAO = value;
					this.SendPropertyChanged("NM_USUARIO_ALTERACAO");
					this.OnNM_USUARIO_ALTERACAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_ALTERACAO", DbType="DateTime")]
		public System.Nullable<System.DateTime> DT_ALTERACAO
		{
			get
			{
				return this._DT_ALTERACAO;
			}
			set
			{
				if ((this._DT_ALTERACAO != value))
				{
					this.OnDT_ALTERACAOChanging(value);
					this.SendPropertyChanging();
					this._DT_ALTERACAO = value;
					this.SendPropertyChanged("DT_ALTERACAO");
					this.OnDT_ALTERACAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NR_ULTIMO_ACESSO", DbType="Int")]
		public System.Nullable<int> NR_ULTIMO_ACESSO
		{
			get
			{
				return this._NR_ULTIMO_ACESSO;
			}
			set
			{
				if ((this._NR_ULTIMO_ACESSO != value))
				{
					this.OnNR_ULTIMO_ACESSOChanging(value);
					this.SendPropertyChanging();
					this._NR_ULTIMO_ACESSO = value;
					this.SendPropertyChanged("NR_ULTIMO_ACESSO");
					this.OnNR_ULTIMO_ACESSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_ULTIMO_ACESSO", DbType="DateTime")]
		public System.Nullable<System.DateTime> DT_ULTIMO_ACESSO
		{
			get
			{
				return this._DT_ULTIMO_ACESSO;
			}
			set
			{
				if ((this._DT_ULTIMO_ACESSO != value))
				{
					this.OnDT_ULTIMO_ACESSOChanging(value);
					this.SendPropertyChanging();
					this._DT_ULTIMO_ACESSO = value;
					this.SendPropertyChanged("DT_ULTIMO_ACESSO");
					this.OnDT_ULTIMO_ACESSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Conta", Storage="_Contas", ThisKey="ID_USUARIO", OtherKey="ID_USUARIO")]
		public EntitySet<Conta> Contas
		{
			get
			{
				return this._Contas;
			}
			set
			{
				this._Contas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Menu_Web_Permissao", Storage="_Menu_Web_Permissaos", ThisKey="ID_USUARIO", OtherKey="ID_USUARIO")]
		public EntitySet<Menu_Web_Permissao> Menu_Web_Permissaos
		{
			get
			{
				return this._Menu_Web_Permissaos;
			}
			set
			{
				this._Menu_Web_Permissaos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Transacao", Storage="_Transacaos", ThisKey="ID_USUARIO", OtherKey="ID_USUARIO_DE")]
		public EntitySet<Transacao> Transacaos
		{
			get
			{
				return this._Transacaos;
			}
			set
			{
				this._Transacaos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Perfil_Usuario", Storage="_Perfil", ThisKey="ID_PERFIL", OtherKey="ID_PERFIL", IsForeignKey=true)]
		public Perfil Perfil
		{
			get
			{
				return this._Perfil.Entity;
			}
			set
			{
				Perfil previousValue = this._Perfil.Entity;
				if (((previousValue != value) 
							|| (this._Perfil.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Perfil.Entity = null;
						previousValue.Usuarios.Remove(this);
					}
					this._Perfil.Entity = value;
					if ((value != null))
					{
						value.Usuarios.Add(this);
						this._ID_PERFIL = value.ID_PERFIL;
					}
					else
					{
						this._ID_PERFIL = default(Nullable<int>);
					}
					this.SendPropertyChanged("Perfil");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Contas(Conta entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Contas(Conta entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_Menu_Web_Permissaos(Menu_Web_Permissao entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Menu_Web_Permissaos(Menu_Web_Permissao entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_Transacaos(Transacao entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Transacaos(Transacao entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_lstTransacao")]
	public partial class vw_lstTransacao
	{
		
		private int _ID_Transacao;
		
		private int _ID_Usuario_De;
		
		private string _NM_Usuario_De;
		
		private string _NR_CPF_De;
		
		private string _NM_Banco_De;
		
		private System.Nullable<decimal> _VL_Saldo_De;
		
		private decimal _VL_Transacao;
		
		private int _ID_Usuario_Para;
		
		private string _NM_Usuario_Para;
		
		private string _NR_CPF_Para;
		
		private string _NM_Banco_Para;
		
		private System.Nullable<decimal> _VL_Saldo_Para;
		
		private System.DateTime _DT_Transacao;
		
		public vw_lstTransacao()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Transacao", DbType="Int NOT NULL")]
		public int ID_Transacao
		{
			get
			{
				return this._ID_Transacao;
			}
			set
			{
				if ((this._ID_Transacao != value))
				{
					this._ID_Transacao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Usuario_De", DbType="Int NOT NULL")]
		public int ID_Usuario_De
		{
			get
			{
				return this._ID_Usuario_De;
			}
			set
			{
				if ((this._ID_Usuario_De != value))
				{
					this._ID_Usuario_De = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_Usuario_De", DbType="VarChar(100)")]
		public string NM_Usuario_De
		{
			get
			{
				return this._NM_Usuario_De;
			}
			set
			{
				if ((this._NM_Usuario_De != value))
				{
					this._NM_Usuario_De = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NR_CPF_De", DbType="VarChar(14)")]
		public string NR_CPF_De
		{
			get
			{
				return this._NR_CPF_De;
			}
			set
			{
				if ((this._NR_CPF_De != value))
				{
					this._NR_CPF_De = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_Banco_De", DbType="VarChar(100)")]
		public string NM_Banco_De
		{
			get
			{
				return this._NM_Banco_De;
			}
			set
			{
				if ((this._NM_Banco_De != value))
				{
					this._NM_Banco_De = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VL_Saldo_De", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> VL_Saldo_De
		{
			get
			{
				return this._VL_Saldo_De;
			}
			set
			{
				if ((this._VL_Saldo_De != value))
				{
					this._VL_Saldo_De = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VL_Transacao", DbType="Decimal(20,2) NOT NULL")]
		public decimal VL_Transacao
		{
			get
			{
				return this._VL_Transacao;
			}
			set
			{
				if ((this._VL_Transacao != value))
				{
					this._VL_Transacao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Usuario_Para", DbType="Int NOT NULL")]
		public int ID_Usuario_Para
		{
			get
			{
				return this._ID_Usuario_Para;
			}
			set
			{
				if ((this._ID_Usuario_Para != value))
				{
					this._ID_Usuario_Para = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_Usuario_Para", DbType="VarChar(100)")]
		public string NM_Usuario_Para
		{
			get
			{
				return this._NM_Usuario_Para;
			}
			set
			{
				if ((this._NM_Usuario_Para != value))
				{
					this._NM_Usuario_Para = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NR_CPF_Para", DbType="VarChar(14)")]
		public string NR_CPF_Para
		{
			get
			{
				return this._NR_CPF_Para;
			}
			set
			{
				if ((this._NR_CPF_Para != value))
				{
					this._NR_CPF_Para = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_Banco_Para", DbType="VarChar(100)")]
		public string NM_Banco_Para
		{
			get
			{
				return this._NM_Banco_Para;
			}
			set
			{
				if ((this._NM_Banco_Para != value))
				{
					this._NM_Banco_Para = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VL_Saldo_Para", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> VL_Saldo_Para
		{
			get
			{
				return this._VL_Saldo_Para;
			}
			set
			{
				if ((this._VL_Saldo_Para != value))
				{
					this._VL_Saldo_Para = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_Transacao", DbType="DateTime NOT NULL")]
		public System.DateTime DT_Transacao
		{
			get
			{
				return this._DT_Transacao;
			}
			set
			{
				if ((this._DT_Transacao != value))
				{
					this._DT_Transacao = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
